Parse manifest directory
dweepgogia/new-manifest-verification pull request #10
Opened 2019-08-07 21:54 UTC by dweepgogia

2019-08-08 19:01 UTC, estroz requested changes
First pass: looks ok overall; the bundle parser could probably use some refactoring to reduce complexity.

2019-08-08 19:01 UTC, estroz commented on cmd/verify.go
> +	if manifestResultList != nil {
Always check if `len(map or slice) ==/!= 0` instead of `==/!= nil`, because `[]type{}` is not `nil` but has a zero length. There are one or two more lines elsewhere that should be changed to the former.

2019-08-08 19:01 UTC, estroz commented on pkg/validate/crd.go
> +		//result := csvInspect(crd)
Remove this line.

2019-08-08 19:01 UTC, estroz commented on pkg/validate/crd.go
> +	scheme := runtime.NewScheme()
You can initialize this scheme once in `Validate` and pass it to `crdInspect`.

2019-08-08 19:01 UTC, estroz commented on pkg/validate/csv.go
> +	if annotations == nil {
Check length

2019-08-08 19:01 UTC, estroz commented on pkg/validate/csv.go
> +	// Expect either `alm-examples` or `old.examples` but not both
If you cannot use both simultaneously, there should be an error returned if they are.

2019-08-08 19:01 UTC, estroz commented on pkg/validate/parser.go
> +		if strings.Contains(scanner.Text(), "kind") {
Better to do something like what we do in the SDK:

```go
// GetTypeMetaFromBytes gets the type and object metadata from b. b is assumed
// to be a single Kubernetes resource manifest.
func GetTypeMetaFromBytes(b []byte) (t metav1.TypeMeta, err error) {
	u := unstructured.Unstructured{}
	r := bytes.NewReader(b)
	dec := yaml.NewYAMLOrJSONDecoder(r, 8)
	// There is only one YAML doc if there are no more bytes to be read or EOF
	// is hit.
	if err := dec.Decode(&u); err == nil && r.Len() != 0 {
		return t, errors.New("error getting TypeMeta from bytes: more than one manifest in b")
	} else if err != nil && err != io.EOF {
		return t, errors.Wrap(err, "error getting TypeMeta from bytes")
	}
	return metav1.TypeMeta{
		APIVersion: u.GetAPIVersion(),
		Kind:       u.GetKind(),
	}, nil
}
```

So you know you're
1. getting a k8s object
2. not accidentally getting another line containing "kind" that is not a YAML field.

Then you can access kind like `typeMeta.Kind`.

2019-08-08 19:01 UTC, estroz commented on pkg/validate/parser.go
> +	_ = filepath.Walk(manifestDirectory, func(path string, f os.FileInfo, err error) error {
Best practice is to never throw away errors. You should either add them to the result or (better) log them.

2019-08-08 19:01 UTC, estroz commented on pkg/validate/parser.go
> +			splitPath := strings.Split(path, "/")
Use `filepath.Base(path)`

2019-08-08 19:01 UTC, estroz commented on pkg/validate/parser.go
> +			if _, ok := manifest.Bundle[path]; !ok {
If `manifest.Bundle` hasn't been initialized this will panic. I suggest doing that above `filepath.Walk()`

2019-08-08 19:01 UTC, estroz commented on pkg/validate/parser.go
> +			if strings.Contains(f.Name(), "package") {
Better to marshal this into a [`PackageManifest`](https://github.com/operator-framework/operator-registry/blob/f5ee2f9/pkg/registry/types.go#L27) and if there's no error you know its of the correct type.

2019-08-08 19:01 UTC, estroz commented on pkg/validate/parser.go
> +			directoryName := strings.TrimSuffix(path, f.Name())
Use `filepath.Dir(path)` here.

2019-08-08 19:01 UTC, estroz commented on pkg/validate/serialize.go
>  		fmt.Println("Validating CSV", errorLog.Name)
```suggestion
		fmt.Printf("Validating CSV %s\n\n", errorLog.Name)
```
and remove `fmt.Println()` below.

2019-08-08 19:01 UTC, gallettilance reviewed
Great work! A few nit picks, questions, requests - let me know

2019-08-08 19:01 UTC, gallettilance commented on pkg/validate/crd.go
> +	return
Did you forget to return the `ManifestResult`?

2019-08-08 19:01 UTC, gallettilance commented on pkg/validate/parser.go
> +			if len(splite) < 2 {
can you put a comment here to explain why you are gating on this specific condition?

2019-08-08 19:01 UTC, gallettilance commented on pkg/validate/parser.go
> +	_ = filepath.Walk(manifestDirectory, func(path string, f os.FileInfo, err error) error {
this function could be shorter by adding a few helpers.

2019-08-08 19:01 UTC, gallettilance commented on pkg/validate/csv.go
> +	// "github.com/pkg/errors"
if this is supposed to be deleted, please delete

2019-08-08 19:01 UTC, gallettilance commented on pkg/validate/serialize.go
>  // it, and calls the unmarshal function on rawYaml.
Either this comment doesn't make much sense for this function or the name of the function is wrong. Why is CSV in the name is this validates any yaml file?

2019-08-08 19:01 UTC, gallettilance commented on pkg/validate/serialize.go
> +		return
why are you not returning `manifestResult` here?

2019-08-08 19:01 UTC, gallettilance commented on pkg/validate/serialize.go
> +		return
here too

2019-08-08 19:01 UTC, gallettilance commented on pkg/validate/serialize.go
> +		return // TODO: update when 'AddObjects' returns an actual error.
also here

2019-08-08 19:01 UTC, gallettilance commented on pkg/validate/serialize.go
> +	return
and here

2019-08-08 19:01 UTC, galletti94 commented on pkg/validate/serialize.go
> +		manifestResultList = append(manifestResultList, ValidateCSVManifest(bundle.CSV))
so you are only validating the CSVs in this commit?

2019-08-08 19:01 UTC, galletti94 commented on pkg/validate/serialize.go
> +		manifestResultList = append(manifestResultList, ValidateCSVManifest(bundle.CSV))
can we try to validate the other stuff too? What's blocking?

2019-08-08 19:04 UTC, estroz commented
We should explore using https://godoc.org/golang.org/x/xerrors for returned errors somehow instead of custom return types. That package (coming to the std lib in Go 1.13) provides a nice interface for creating, type checking, and unwrapping errors. Outside of this PR's scope though.

2019-08-08 19:28 UTC, dweepgogia commented
> We should explore using https://godoc.org/golang.org/x/xerrors for returned errors somehow instead of custom return types. That package (coming to the std lib in Go 1.13) provides a nice interface for creating, type checking, and unwrapping errors. Outside of this PR's scope though.

We decided to go with custom error reporting, especially the way we have defined it, because it's compatible with the way Kubernetes reports errors for all the validations they're performing. You can have a look at their definition here: https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/field/errors.go#L31. 
If in the future, we move to the upstream this library would support that transition, and there should not be many changes required.

2019-08-08 19:30 UTC, dweepgogia commented on cmd/verify.go
> +	if manifestResultList != nil {
Good to learn that, thanks!

2019-08-08 19:39 UTC, dweepgogia commented on pkg/validate/csv.go
> +	// Expect either `alm-examples` or `old.examples` but not both
I'm not sure if that should raise an error. I can return a warning instead if mentioning both would not affect the operator.

2019-08-08 19:45 UTC, dweepgogia commented on pkg/validate/parser.go
> +	_ = filepath.Walk(manifestDirectory, func(path string, f os.FileInfo, err error) error {
It does look like that I'm throwing away the error but I am not. All the `return` statements in the `walk` function are returning `nil`. Instead, I'm appending the errors in `manifestResult` object.

2019-08-08 19:50 UTC, dweepgogia commented on pkg/validate/crd.go
> +	return
I'm using golang's `Named Return` concept. See https://tour.golang.org/basics/7.

2019-08-08 19:54 UTC, dweepgogia commented on pkg/validate/serialize.go
> +		return
Same as above

2019-08-08 19:54 UTC, dweepgogia commented on pkg/validate/serialize.go
> +		return
Same as above.

2019-08-08 19:54 UTC, dweepgogia commented on pkg/validate/serialize.go
> +		return // TODO: update when 'AddObjects' returns an actual error.
Same as above.

2019-08-08 19:54 UTC, dweepgogia commented on pkg/validate/serialize.go
> +	return
Same as above.

2019-08-08 20:19 UTC, galletti94 commented on pkg/validate/crd.go
> +	return
Sweet! Didn't know about this - pretty cool

2019-08-12 19:44 UTC, dweepgogia commented on pkg/validate/parser.go
> +			if strings.Contains(f.Name(), "package") {
[json.Unmarshal()](https://golang.org/pkg/encoding/json/#Unmarshal) does not return an error if the values in the source do not correspond to the values in the target - it just ignores them.

2019-08-12 19:51 UTC, estroz commented on pkg/validate/parser.go
> +			if strings.Contains(f.Name(), "package") {
You can use [`yaml.UnmarshalStrict`](https://godoc.org/sigs.k8s.io/yaml#UnmarshalStrict).

2019-08-12 19:53 UTC, estroz commented on pkg/validate/csv.go
> +	// Expect either `alm-examples` or `old.examples` but not both
Either return a warning or change the comment.

2019-08-12 19:57 UTC, estroz commented on pkg/validate/parser.go
> +	_ = filepath.Walk(manifestDirectory, func(path string, f os.FileInfo, err error) error {
You're not checking the `err` argument, and overwriting it [here](https://github.com/dweepgogia/new-manifest-verification/blob/c5f69a5c86f1832146e69df342b6d659baba01bf/pkg/validate/parser.go#L86). Better to check and ignore it.

2019-08-12 20:14 UTC, dweepgogia commented on pkg/validate/parser.go
> +			if strings.Contains(f.Name(), "package") {
That's not returning an error either.

2019-08-12 20:19 UTC, dweepgogia commented on pkg/validate/csv.go
> +	// Expect either `alm-examples` or `old.examples` but not both
Sure.

2019-08-12 20:28 UTC, dweepgogia commented on pkg/validate/parser.go
> +			if strings.Contains(f.Name(), "package") {
I was using a different `yaml` package. Working now. Thanks!

2019-08-12 21:25 UTC, dweepgogia commented on pkg/validate/parser.go
> +		if strings.Contains(scanner.Text(), "kind") {
How about I use `yaml.UnmarshalStrict` for identifying `CSVs` and `CRDs` the way I use it for `package` files?

2019-08-13 19:33 UTC, dweepgogia commented
Updated the PR with suggested changes and added two additional commits for `package` and `bundle` validators. Please review when you get a chance.

Note: will connect the `CRD` and `package` validators in upcoming PRs.

2019-08-13 21:28 UTC, estroz commented
@dweepgogia sounds good, keep the current error type as-is.

2019-08-14 00:57 UTC, dweepgogia commented
Thanks for reviewing @estroz and @galletti94

2019-08-19 16:26 UTC, estroz requested changes
While the functional ordering here works, its a little rough. I'd rather not see print statements in functions called by non-top level functions and returned values thrown away, ex. [here](https://github.com/dweepgogia/new-manifest-verification/pull/10/commits/79a4c672b5e609125bd5872c941751bbc966cb0c#diff-bdc50831c9bdaed93469e0e72394e9e0R184). I'd like to see a flow like:

1. Parse files/directory
    * You might want to add type information to each file, ex. "this file is a CSV", so you can validate them by type
1. Run validator helpers on each file parsed
1. Check results and print errors

This flow is cleaner, more logical, and uses function return values as another library user would.

2019-08-26 23:14 UTC, merged